DEFINES=USE_SPI_DMA
#DEFINES+=NDEBUG

EXTRA_INCLUDES=../lib-osc/include ../lib-hal/include ../lib-network/include ../lib-properties/include ../lib-lightset/include

include ../firmware-template-gd32/lib/Rules.mk